.\" Formater ce fichier par la commande :
.\" groff -man -Tutf8 codemetre.1
.\"
.TH CODEMETRE 1 "AOÛT 2008" Linux "Manuel utilisateur"
.SH NOM
codemetre \- comptage de ligne de fichiers source
.SH SYNOPSIS
.B codemetre
[--ada|--c++|--eiffel] [--code] [--commentaire] [--total] [--analyse|--diff] [--effort|--normal] [--lot] [--] FICHIER...
.SH DESCRIPTION
.B Codemetre
permet de comptabiliser le nombre de lignes de code et/ou de commentaires contenues dans des fichiers source. Il permet également d'évaluer l'effort réalisé entre deux versions d'un même fichier, toujours en nombre de lignes.
.SH OPTIONS PARTICULIÈRES
L'option "--" peut être utilisée pour s'assurer que tous les arguments la suivant seront considérés comme des noms de fichier. Ceci peut s'avérer utile lorsqu'un fichier à analyser porte le nom d'une option.

L'option "--lot" permet de spécifier un traitement par lots, c'est-à-dire que les entrées sont considérées comme des liste de fichiers sur lesquels mener la métrologie.
.SH LANGAGES SUPPORTÉS
Si aucun langage n'est spécifié, alors
.B codemetre
essaiera de déterminer celui-ci à partir de l'extension du fichier. Si par contre un langage est spécifié, alors ce choix prévaut quelque soit l'extension du ou des fichiers à mesurer. Les options sont les suivantes :
.IP --ada
Respecte le standard Ada95. Extensions ".ads" et ".adb".
.IP --c++
Respecte la norme C++ ISO/IEC 14882:2003. Extensions ".hpp", ".C", ".cc" et ".cpp".
.IP --eiffel
Respecte le standard Eiffel tel que définit dans le livre "Eiffel, le langage" de B. Meyer paru chez InterEditions en 1994. Extension ".e".
.SH SPECTRE DE L'ANALYSE
.B codemetre
sait différencier le code des commentaires, et peut ne prendre en compte que l'un ou l'autre. Attention, une seule des options suivantes est autorisée lors d'une demande d'analyse lexicale ou de comparaison différentielle. Dans le cas d'un simple comptage de ligne sans comparaison, on peut spécifier autant de ces options que l'on souhaite.
.IP --code
Ne conserve pour l'analyse que les lignes de code.
.IP --commentaire
Ne conserve pour l'analyse que les lignes de commentaire.
.IP --total
Prend en compte à la fois le code et les commentaires lors de l'analyse.
.SH COMMANDES
.IP "<fichier> ..."
Compte pour chaque
.I fichier
le nombre de lignes total, de code ou de commentaire selon les options qui auront été passées. Par défaut, le nombre de lignes de code et de commentaires sont produits.
.IP "--diff <avant> <après>"
Détermine l'effort minimal qui a été réalisé pour transformer le fichier
.I <avant>
en le fichier
.I <après>.
Ces métriques sont proposées selon un modèle assez intuitif (voir plus loin). Pour préciser qu'un fichier n'existait pas, ou n'existe plus, on peut utiliser le mot-clef spécifique
.B -rien-.
.IP "--analyse <fichier> ..."
Produit pour chaque
.I <fichier>
en entrée un fichier suffixé
.I .codemetre
isolant chaque terme et en le qualifiant CODE ou COMMENTAIRE.
.SH MODÈLE DIFFÉRENTIEL
Il existe plusieurs modèles de comptage différentiel, chacun étant détaillé dans une section plus loin. Le modèle normal est le modèle par défaut.
.IP "--normal"
produit trois métriques fondamentales qui permettent d'en construire d'autre (comme l'effort par exemple)
.IP "--effort"
détermine, en pourcentage de la taille du fichier, l'effort qui a été fourni entre les deux versions.
.SH MODÈLE DIFFÉRENTIEL : NORMAL
La définition des trois métriques du modèle normal est :
.IP A
dénombre les lignes de l'ancienne version du fichier.
.IP N
dénombre les lignes de la nouvelle version du fichier.
.IP C
dénombre les lignes communes aux deux versions du fichier.
.SH MODÈLE DIFFÉRENTIEL : EFFORT
L'effort entre deux versions d'un fichier est définit comme le nombre de lignes nouvelles sur la taille du fichier. Si l'on prend la notation du modèle normal, cela correspond à (N-C)/N.
.SH DIAGNOSTICS
Si malgré le forçage d'un choix de langage, l'analyse d'un fichier venait à échouer, un message détaillé est produit en indiquant l'endroit.
.SH TOLÉRANCE PAR RAPPORT AUX NORMES OFFICIELLES
.IP Ada95
théoriquement, seuls les caractères ASCII 7 bits sont autorisés pour les constantes littérales.
.B Codemetre
tolère tous les caractères 8 bits.
.SH BOGUES ET LIMITATIONS
.B Codemetre
ne fait pas l'expansion des macro-commandes du C++, même si ceci ne modifierait pas les mesures produites. En effet, certaines macros-commandes peuvent être définies ailleurs que dans le fichier sous analyse, et
.B codemetre
n'a pas connaissance de l'organisation du projet et des règles de visibilités entre répertoires.

Lors d'une mesure différentielle, tout bloc déplacé n'est a priori pas considéré commun aux deux versions de fichier, parce que l'impact de ce mouvement ne peut être évalué.

Concernant Eiffel,
.B codemetre
ne supporte pas tous les foisonnements de syntaxe particuliers à chaque compilateur.
.SH AUTEUR
Guillaume Lemaître	<guillaume.lemaitre@gmail.com>
.SH "VOIR AUSSI"
.BR diff (1),
.BR wc(1).
